### ISSUE TITLE
Poor error handling on undefineds

### ISSUE THREAD

**Issue by davidrenne** [rma-consulting/react-xhr-uploader#18]
https://github.com/davidrenne/react-xhr-uploader/blob/master/src/index.js#L123
https://github.com/davidrenne/react-xhr-uploader/blob/master/src/index.js#L190
https://github.com/davidrenne/react-xhr-uploader/blob/master/src/index.js#L239 

We have a use for this where there is some kind of bad state where a file exists on the map, but then size is gone after an upload so unhandled exceptions happen.

I think we are implementing a try/catch around the xhr-uploader JSX in the meantime which should catch the errors in this state on a re-render, but I wanted you guys to be aware to run some tests where possibly the object might undefined specifically our problem is line 239 where item.file becomes undefined and there is no try/catch to supress the error and the error propagates up the stack if the caller doesnt try catch.

Its best to check for undefineds and bail out on your end preferably.  I will let you know how our try/catch works but I dont feel like forking or doing a pull request since we might just handle it on the caller end to limit the stack error from going all the way to the top

**Comment by harunhasdal** [comment]
Thanks for reporting @davidrenne, I haven't come across such a case where the `item` is there but `item.file` is missing yet. All valid points though. Instead of using try catch as you suggested, I think we should improve the undefined checks and be a bit more defensive on it. I would avoid `try/catch` wrapping many lines as it has a potential to suppress any other error which may occur. I will hopefully push something in a few days.

**Comment by harunhasdal** [comment]
I am also considering to use `componentDidCatch` for rendering something decent instead of crashing.
